name: Auto Close Issue

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  close-not-reproducible-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          BODY: >
            Thanks for raising this issue 🙏<br />
            <br />
            Unfortunately, we are closing the issue as no reproducible samples were provided within 7 days.<br />
            If there are any updates, please reopen this issue or create new one.<br />
            <br />
            If you have any questions please reach out to us on our [Discord](https://discord.webdriver.io/)<br />
            channel. We are happy to help you out there.
        with:
          github-token: ${{ secrets.WDIO_BOT_GITHUB_TOKEN }}
          script: |
            const labelName = 'Reproducible Example Missing'
            const daysBeforeClose = 7
            const perPage = 100

            const now = new Date()
            const msInDay = 24 * 60 * 60 * 1000
            const iterator = github.paginate.iterator(github.rest.issues.listForRepo, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                labels: [labelName],
                per_page: perPage,
            })

            for await (const { data: issues } of iterator) {
              for (const issue of issues) {
                if (issue.pull_request) {
                  continue
                }

                const events = await github.paginate(
                  github.rest.issues.listEventsForTimeline,
                  {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    per_page: perPage
                  }
                )

                const labelEvent = events.find(
                  e => e.event === 'labeled' && e.label?.name === labelName
                )

                if (!labelEvent) {
                  continue
                }

                const labeledAt = new Date(labelEvent.created_at)
                const updatedAt = new Date(issue.updated_at)
                const targetDate = updatedAt > labeledAt ? updatedAt : labeledAt

                const diffDays = Math.floor((now - targetDate) / msInDay)
                if (diffDays >= daysBeforeClose) {
                  console.log(`Closing issue #${issue.number} (inactive ${diffDays} days after label)`)

                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    body: process.env.BODY,
                  })

                  await github.rest.issues.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    state: 'closed'
                  })
                }
              }
            }
