name: CI

on:
    push:
        branches:
            - main
            - v[0-9]+
        tags:
            - v[0-9]+.[0-9]+.[0-9]+*
    pull_request:

jobs:
    build:
        name: Build
        uses: ./.github/workflows/ci-build.yml
        with:
            os: 'ubuntu-latest'

    lint:
        name: Lint
        needs: [build]
        uses: ./.github/workflows/ci-lint.yml

    unit:
        name: Unit
        uses: ./.github/workflows/ci-unit.yml
