name: Manual Publish

on:
    workflow_dispatch:
        inputs:
            releaseType:
                description: 'Release Type'
                required: true
                type: choice
                default: 'patch'
                options:
                    - patch
                    - minor
                    - major
                    - premajor
                    - preminor
                    - prepatch
            publishMarketplace:
                description: 'Publish on Visual Studio Marketplace?'
                required: true
                type: choice
                default: 'yes'
                options:
                    - 'yes'
                    - 'no'

jobs:
    release:
        permissions:
            contents: write
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: 👷 Checkout
              uses: actions/checkout@v4
              with:
                  ref: 'main'
                  fetch-depth: 0

            - name: 🛠️ Setup workspace
              uses: ./.github/workflows/actions/setup-workspace
              with:
                  node-version: '20'

            - name: 🪄 Generate Prerelease patch version number
              id: gen-pre-release-ver
              env:
                  RELEASE_TYPE: ${{ github.event.inputs.releaseType }}
              run: |
                  if [[ "${RELEASE_TYPE}" == "pre"* ]]; then
                      VERSION="$(node .github/scripts/genPreReleaseVersion.js)"
                      echo "version=${VERSION}" >> $GITHUB_OUTPUT
                  else
                      echo "version=" >> $GITHUB_OUTPUT
                  fi

            - name: 🚧 Bump the version
              id: bump
              run: |
                  pnpm lerna version ${{github.event.inputs.releaseType}} --no-push --exact --preid next --yes -m "chore(release): %s"
              env:
                  NODE_ENV: production
                  GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
                  VSCODE_WDIO_PRE_RELEASE_PATCH_NUMBER: ${{ steps.gen-pre-release-ver.outputs.version }}

            - name: 🛫 Build and publish as pre-release
              if: ${{  github.event.inputs.publishMarketplace == 'yes' && startsWith(github.event.inputs.releaseType, 'pre') }}
              run: |
                  pnpm run publish:next
              env:
                  NODE_ENV: production
                  GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
                  VSCODE_WDIO_PRE_RELEASE_PATCH_NUMBER: ${{ steps.gen-pre-release-ver.outputs.version }}

            - name: 🚀 Build and publish
              if: ${{  github.event.inputs.publishMarketplace == 'yes' && !startsWith(github.event.inputs.releaseType, 'pre') }}
              run: |
                  pnpm run publish
              env:
                  NODE_ENV: production
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
                  GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

            - name: 📝 Create the Github Release
              run: |
                  pnpm --filter @vscode-wdio/release run release-note
              env:
                  GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
                  VSCODE_WDIO_RELEASE_NOTE: ${{ steps.bump.outputs.changelog }}
